#!/usr/bin/env bash

# Use $# to get number of command line arguments.
if [ $# -gt 0 ]; then
	~/tomato/main.py "$@"
else
	ipython -i ~/tomato/myinspect.py
fi

if [ "$1" = "-r" -o "$1" = "report" ]; then
	gnome-open ~/tomato/report.png
else
	sleep .5 && tmux refresh-client -S &
fi
