#!/usr/bin/env bash

# Use $# to get number of command line arguments.

if [ "$1" = 't' -o "$1" = "-t" ]; then
	~/tomato/main.py --toggle
	tmux refresh-client -S
elif [ "$1" = 'p' -o "$1" = "-p" ]; then
	~/tomato/main.py --report
	gnome-open ~/tomato/report.png
elif [ "$1" = 'm' -o "$1" = "-m" ]; then
	~/tomato/main.py --monitor $2
	tmux refresh-client -S
else
	ipython -i ~/tomato/myinspect.py
fi
